language: python
cache: pip
sudo: false
if: (type = push AND branch IN (master)) OR (type = pull_request)
python:
  - 3.6
env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=master
matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: DJANGO=master }
    - { python: "3.6", env: DJANGO=3.0 }
    - { python: "3.6", env: DJANGO=2.2 }
  allow_failures:
    - env: DJANGO=master
install:
  - pip install -e .
  - pip install -r requirements/test.txt
script: py.test --cov=django_slugify_processor
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
