language: python
cache: pip

if: (type = push AND branch IN (master)) OR (type = pull_request)

python:
    - "2.7"
    - "3.4"
    - "3.5"

sudo: false

env:
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=master

matrix:
    fast_finish: true
    include:
      - { python: "3.6", env: DJANGO=master }
      - { python: "3.6", env: DJANGO=1.11 }
      - { python: "3.6", env: DJANGO=2.0 }
    exclude:
      - { python: "2.7", env: DJANGO=master }
      - { python: "2.7", env: DJANGO=2.0 }
      - { python: "3.4", env: DJANGO=master }

    allow_failures:
      - env: DJANGO=master

install:
    - pip install tox tox-travis codecov pytest-cov

script:
    - tox -- --cov  # positional args to pass into tox.ini

after_success:
    - codecov

notifications:
    email: false
